# Stage 1: просто копируем файлы фронта
FROM nginx:1.25.2-alpine
# Копируем конфиг nginx
COPY devops/docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Копируем весь фронт в папку html nginx
COPY ../front-end/ /opt/services/helloapp/helloapp_frontend/dist

# Экспонируем порт
EXPOSE 80

# Запуск nginx
CMD ["nginx", "-g", "daemon off;"]
